name: currency
version: 0.0.6
homepage: https://github.com/wurst-case/currency
repository: https://github.com/wurst-case/currency
description: >-
  Contains code to deal with currencies.
environment:
  sdk: '>3.0.0'
documentation: https://github.com/wurst-case/currency